language: go

dist: focal
sudo: required

go: "1.17.6"

jobs:
  include:
    - arch: amd64
    - arch: arm64-graviton2
      virt: vm
      group: edge
    - arch: amd64
      name: "amd64-race"
      if: type != pull_request
      env:
        - RACE=1
        - BASE_IMAGE=quay.io/cilium/cilium-runtime:ec699d558d3b1c96e83479675b9ad720399e8e19@sha256:45405457453497a6bd15bfb10aa72a82b5f36af6c3e7219043aa4146f5032df1
        - LOCKDEBUG=1

# Disabled due to a compilation issue: https://github.com/cilium/cilium/issues/13252
#    - arch: arm64-graviton2
#      name: "arm64-graviton2-race"
#      if: type != pull_request
#      env:
#        - RACE=1
#        - BASE_IMAGE=quay.io/cilium/cilium-runtime:ec699d558d3b1c96e83479675b9ad720399e8e19@sha256:45405457453497a6bd15bfb10aa72a82b5f36af6c3e7219043aa4146f5032df1
#        - LOCKDEBUG=1
#      virt: vm
#      group: edge

if: branch = master OR type = pull_request

addons:
  apt:
    packages:
      - kernel-package
      - gnupg
      - libncurses5

before_install: ./.travis/prepare.sh

before_script:
  - export PATH=/usr/local/clang/bin:$PATH

script: ./.travis/build.sh

notifications:
  email: false
